### ISSUE TITLE
Won't install correctly

### ISSUE THREAD

**Issue by ShaCP** [algolia/marvel-search#5]
There's a lot of errors when trying to install. A lot of issues with the packages. Any chance of an update?

**Comment by pixelastic** [comment]
Ouch, this repository hasn't been updated in 3-4 years, and I no longer work at Algolia. It's going to be tough.

I had a look to see what I could do, and it seems that `yarn install` hangs on some compilation errors, apparently linked to the brunch auto-reload feature as well as node-sass compiling. Both those technologies are outdated today and I don't see an easy fix.

Maybe trying to build with an older node version could work? Alternatively, you could check the `gh-pages` branch, where the final built website is available. Depending on what you'd like to do it may help.
